
export interface LuzResponse {
    "00-01": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"01-02": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"02-03": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"03-04": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"04-05": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"05-06": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"06-07": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"07-08": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"08-09": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"09-10": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"10-11": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"11-12": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"12-13": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"13-14": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"14-15": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"15-16": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"16-17": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"17-18": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"18-19": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"19-20": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"20-21": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"21-22": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"22-23": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    },"23-24": {
        date: string,
        hour: string,
        isCheap: boolean,
        isUnderAvg: boolean,
        market: string,
        price: number,
        units: string
    }
}
